! Generated by unified microphysics wrapper generator on 2015-07-29T18:25:11.884325

module microphysics_initialisation
   use microphysics_register, only: n_species, register_compressible_species, n_gases, n_solids
   use microphysics_register, only: q_flux_function

   implicit none

   public init

contains
   subroutine init(microphysics_implementation__in)
      character(len=*), optional, intent(in) :: microphysics_implementation__in
      character(len=32) :: configuration = ''

      if (present(microphysics_implementation__in)) then
         configuration = microphysics_implementation__in
      else
         namelist /microphysics_config/ configuration

         open(1, file='input/microphysics.nml',form='formatted',status='old')
         read(1, nml=microphysics_config)
         close(1)
      endif

      call register_compressible_species('dry_air')
      call register_compressible_species('water_vapour')

      if (configuration == '') then
         print *, "Please choose a microphysics model to use. The available models are:"
         print *, "  no_ice"
         
    else if (configuration .eq. "no_ice") then
        call mphys_wrapper_no_ice()
    
      else
         print *, "Error the chosen microphysics implementation wasn't found"
         call exit(-1)
      endif

      print *, "Microphysics init complete, tracers:"
      print *, "  incompressible:", n_solids
      print *, "  compressible:", n_gases

   end subroutine init

   
    subroutine mphys_wrapper_no_ice
        use mphys_no_ice, only: init, calc_dq !, n_moments
        !n_tracers = size(n_moments)
        !if (maxval(n_moments) > n_moments__max) then
        !    n_moments__max = maxval(n_moments)
        !endif
        !call allocate_local()
        call init()
        q_flux_function => calc_dq
    end subroutine mphys_wrapper_no_ice


end module microphysics_initialisation
