!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitmicrophysics_constants(f2pysetupfunc)
      use microphysics_constants, only : L_cond
      use microphysics_constants, only : cp_v
      use microphysics_constants, only : cp_i
      use microphysics_constants, only : rho_w
      use microphysics_constants, only : cp_l
      use microphysics_constants, only : R_v
      use microphysics_constants, only : kreal
      use microphysics_constants, only : ps0
      use microphysics_constants, only : cp_d
      use microphysics_constants, only : int8
      use microphysics_constants, only : cv_d
      use microphysics_constants, only : int4
      use microphysics_constants, only : T0
      use microphysics_constants, only : R_d
      use microphysics_constants, only : cv_i
      use microphysics_constants, only : epsmach
      use microphysics_constants, only : cv_l
      use microphysics_constants, only : real8
      use microphysics_constants, only : kint
      use microphysics_constants, only : cv_v
      use microphysics_constants, only : real2
      use microphysics_constants, only : real4
      external f2pysetupfunc
      call f2pysetupfunc(L_cond,cp_v,cp_i,rho_w,cp_l,R_v,kreal,ps0,cp_d,&
     &int8,cv_d,int4,T0,R_d,cv_i,epsmach,cv_l,real8,kint,cv_v,real2,real&
     &4)
      end subroutine f2pyinitmicrophysics_constants

      subroutine f2pywrap_microphysics_common_thermal_conductivity (ther&
     &mal_conductivityf2pywrap, temp)
      use microphysics_common, only : thermal_conductivity
      real(kind=8) temp
      real(kind=8) thermal_conductivityf2pywrap
      thermal_conductivityf2pywrap = thermal_conductivity(temp)
      end subroutine f2pywrap_microphysics_common_thermal_conductivity
      subroutine f2pywrap_microphysics_common_water_vapour_diffusivity (&
     &water_vapour_diffusivityf2pywrap, temp, pressure)
      use microphysics_common, only : water_vapour_diffusivity
      real(kind=8) temp
      real(kind=8) pressure
      real(kind=8) water_vapour_diffusivityf2pywrap
      water_vapour_diffusivityf2pywrap = water_vapour_diffusivity(temp, &
     &pressure)
      end subroutine f2pywrap_microphysics_common_water_vapour_diffusivi&
     &ty
      subroutine f2pywrap_microphysics_common_saturation_vapour_pressure&
     & (saturation_vapour_pressuref2pywrap, temp)
      use microphysics_common, only : saturation_vapour_pressure
      real(kind=8) temp
      real(kind=8) saturation_vapour_pressuref2pywrap
      saturation_vapour_pressuref2pywrap = saturation_vapour_pressure(te&
     &mp)
      end subroutine f2pywrap_microphysics_common_saturation_vapour_pres&
     &sure
      
      subroutine f2pyinitmicrophysics_common(f2pysetupfunc)
      interface 
      subroutine f2pywrap_microphysics_common_thermal_conductivity (ther&
     &mal_conductivityf2pywrap, thermal_conductivity, temp)
      real(kind=8) thermal_conductivity
      real(kind=8) temp
      real(kind=8) thermal_conductivityf2pywrap
      end subroutine f2pywrap_microphysics_common_thermal_conductivity 
      subroutine f2pywrap_microphysics_common_water_vapour_diffusivity (&
     &water_vapour_diffusivityf2pywrap, water_vapour_diffusivity, temp, &
     &pressure)
      real(kind=8) water_vapour_diffusivity
      real(kind=8) temp
      real(kind=8) pressure
      real(kind=8) water_vapour_diffusivityf2pywrap
      end subroutine f2pywrap_microphysics_common_water_vapour_diffusivi&
     &ty 
      subroutine f2pywrap_microphysics_common_saturation_vapour_pressure&
     & (saturation_vapour_pressuref2pywrap, saturation_vapour_pressure, &
     &temp)
      real(kind=8) saturation_vapour_pressure
      real(kind=8) temp
      real(kind=8) saturation_vapour_pressuref2pywrap
      end subroutine f2pywrap_microphysics_common_saturation_vapour_pres&
     &sure
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_microphysics_common_thermal_conductivi&
     &ty,f2pywrap_microphysics_common_water_vapour_diffusivity,f2pywrap_&
     &microphysics_common_saturation_vapour_pressure)
      end subroutine f2pyinitmicrophysics_common

      subroutine f2py_microphysics_register_getdims_moments(r,s,f2pysetd&
     &ata,flag)
      use microphysics_register, only: d => moments

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_microphysics_register_getdims_moments
      subroutine f2py_microphysics_register_getdims_cv_solids(r,s,f2pyse&
     &tdata,flag)
      use microphysics_register, only: d => cv_solids

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_microphysics_register_getdims_cv_solids
      subroutine f2py_microphysics_register_getdims_cv_gases(r,s,f2pyset&
     &data,flag)
      use microphysics_register, only: d => cv_gases

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_microphysics_register_getdims_cv_gases
      subroutine f2py_microphysics_register_getdims_cp_solids(r,s,f2pyse&
     &tdata,flag)
      use microphysics_register, only: d => cp_solids

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_microphysics_register_getdims_cp_solids
      subroutine f2py_microphysics_register_getdims_cp_gases(r,s,f2pyset&
     &data,flag)
      use microphysics_register, only: d => cp_gases

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_microphysics_register_getdims_cp_gases
      
      subroutine f2pyinitmicrophysics_register(f2pysetupfunc)
      use microphysics_register, only : n_gases
      use microphysics_register, only : moments
      use microphysics_register, only : idx_dry_air
      use microphysics_register, only : n_moments__max
      use microphysics_register, only : n_solids
      use microphysics_register, only : idx_rain
      use microphysics_register, only : cv_solids
      use microphysics_register, only : idx_cice
      use microphysics_register, only : cv_gases
      use microphysics_register, only : idx_cwater
      use microphysics_register, only : cp_solids
      use microphysics_register, only : n_species
      use microphysics_register, only : idx_water_vapour
      use microphysics_register, only : idx_graupel
      use microphysics_register, only : cp_gases
      use microphysics_register, only : register_compressible_species
      use microphysics_register, only : register_incompressible_species
      external f2pysetupfunc
      external f2py_microphysics_register_getdims_moments
      external f2py_microphysics_register_getdims_cv_solids
      external f2py_microphysics_register_getdims_cv_gases
      external f2py_microphysics_register_getdims_cp_solids
      external f2py_microphysics_register_getdims_cp_gases
      call f2pysetupfunc(n_gases,f2py_microphysics_register_getdims_mome&
     &nts,idx_dry_air,n_moments__max,n_solids,idx_rain,f2py_microphysics&
     &_register_getdims_cv_solids,idx_cice,f2py_microphysics_register_ge&
     &tdims_cv_gases,idx_cwater,f2py_microphysics_register_getdims_cp_so&
     &lids,n_species,idx_water_vapour,idx_graupel,f2py_microphysics_regi&
     &ster_getdims_cp_gases,register_compressible_species,register_incom&
     &pressible_species)
      end subroutine f2pyinitmicrophysics_register

      subroutine f2pywrap_microphysics_pylib_dimensions_valid (dimension&
     &s_validf2pywrap, n_gases, n_solids, n_moments__max)
      use microphysics_pylib, only : dimensions_valid
      integer n_gases
      integer n_solids
      integer n_moments__max
      logical dimensions_validf2pywrap
      dimensions_validf2pywrap = .not.(.not.dimensions_valid(n_gases, n_&
     &solids, n_moments__max))
      end subroutine f2pywrap_microphysics_pylib_dimensions_valid
      subroutine f2pywrap_microphysics_pylib_init_called (init_calledf2p&
     &ywrap)
      use microphysics_pylib, only : init_called
      logical init_calledf2pywrap
      init_calledf2pywrap = .not.(.not.init_called())
      end subroutine f2pywrap_microphysics_pylib_init_called
      
      subroutine f2pyinitmicrophysics_pylib(f2pysetupfunc)
      use microphysics_pylib, only : init
      use microphysics_pylib, only : calc_dq
      interface 
      subroutine f2pywrap_microphysics_pylib_dimensions_valid (dimension&
     &s_validf2pywrap, dimensions_valid, n_gases, n_solids, n_moments__m&
     &ax)
      logical dimensions_valid
      integer n_gases
      integer n_solids
      integer n_moments__max
      logical dimensions_validf2pywrap
      end subroutine f2pywrap_microphysics_pylib_dimensions_valid 
      subroutine f2pywrap_microphysics_pylib_init_called (init_calledf2p&
     &ywrap, init_called)
      logical init_called
      logical init_calledf2pywrap
      end subroutine f2pywrap_microphysics_pylib_init_called
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(init,calc_dq,f2pywrap_microphysics_pylib_dimens&
     &ions_valid,f2pywrap_microphysics_pylib_init_called)
      end subroutine f2pyinitmicrophysics_pylib


