/* File: unified_microphysicsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Jul 31 16:54:52 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *unified_microphysics_error;
static PyObject *unified_microphysics_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(unified_microphysics_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = unified_microphysics_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = unified_microphysics_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = unified_microphysics_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/**************************** thermal_conductivity ****************************/
static char doc_f2py_rout_unified_microphysics_microphysics_common_thermal_conductivity[] = "\
thermal_conductivity = thermal_conductivity(temp)\n\nWrapper for ``thermal_conductivity``.\
\n\nParameters\n----------\n"
"temp : input float\n"
"\nReturns\n-------\n"
"thermal_conductivity : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_unified_microphysics_microphysics_common_thermal_conductivity(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double thermal_conductivity = 0;
  double temp = 0;
  PyObject *temp_capi = Py_None;
  static char *capi_kwlist[] = {"temp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:unified_microphysics.microphysics_common.thermal_conductivity",\
    capi_kwlist,&temp_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable temp */
    f2py_success = double_from_pyobj(&temp,temp_capi,"unified_microphysics.microphysics_common.thermal_conductivity() 1st argument (temp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable thermal_conductivity */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&thermal_conductivity,&temp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",thermal_conductivity);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable thermal_conductivity */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of thermal_conductivity ************************/

/************************** water_vapour_diffusivity **************************/
static char doc_f2py_rout_unified_microphysics_microphysics_common_water_vapour_diffusivity[] = "\
water_vapour_diffusivity = water_vapour_diffusivity(temp,pressure)\n\nWrapper for ``water_vapour_diffusivity``.\
\n\nParameters\n----------\n"
"temp : input float\n"
"pressure : input float\n"
"\nReturns\n-------\n"
"water_vapour_diffusivity : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_unified_microphysics_microphysics_common_water_vapour_diffusivity(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double water_vapour_diffusivity = 0;
  double temp = 0;
  PyObject *temp_capi = Py_None;
  double pressure = 0;
  PyObject *pressure_capi = Py_None;
  static char *capi_kwlist[] = {"temp","pressure",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:unified_microphysics.microphysics_common.water_vapour_diffusivity",\
    capi_kwlist,&temp_capi,&pressure_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable pressure */
    f2py_success = double_from_pyobj(&pressure,pressure_capi,"unified_microphysics.microphysics_common.water_vapour_diffusivity() 2nd argument (pressure) can't be converted to double");
  if (f2py_success) {
  /* Processing variable water_vapour_diffusivity */
  /* Processing variable temp */
    f2py_success = double_from_pyobj(&temp,temp_capi,"unified_microphysics.microphysics_common.water_vapour_diffusivity() 1st argument (temp) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&water_vapour_diffusivity,&temp,&pressure);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",water_vapour_diffusivity);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  /* End of cleaning variable water_vapour_diffusivity */
  } /*if (f2py_success) of pressure*/
  /* End of cleaning variable pressure */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************** end of water_vapour_diffusivity **********************/

/************************* saturation_vapour_pressure *************************/
static char doc_f2py_rout_unified_microphysics_microphysics_common_saturation_vapour_pressure[] = "\
saturation_vapour_pressure = saturation_vapour_pressure(temp)\n\nWrapper for ``saturation_vapour_pressure``.\
\n\nParameters\n----------\n"
"temp : input float\n"
"\nReturns\n-------\n"
"saturation_vapour_pressure : float";
/* #declfortranroutine# */
static PyObject *f2py_rout_unified_microphysics_microphysics_common_saturation_vapour_pressure(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double saturation_vapour_pressure = 0;
  double temp = 0;
  PyObject *temp_capi = Py_None;
  static char *capi_kwlist[] = {"temp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:unified_microphysics.microphysics_common.saturation_vapour_pressure",\
    capi_kwlist,&temp_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable temp */
    f2py_success = double_from_pyobj(&temp,temp_capi,"unified_microphysics.microphysics_common.saturation_vapour_pressure() 1st argument (temp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable saturation_vapour_pressure */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&saturation_vapour_pressure,&temp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",saturation_vapour_pressure);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable saturation_vapour_pressure */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************* end of saturation_vapour_pressure *********************/

/*********************** register_compressible_species ***********************/
static char doc_f2py_rout_unified_microphysics_microphysics_register_register_compressible_species[] = "\
register_compressible_species(var_name,[cp__in,cv__in])\n\nWrapper for ``register_compressible_species``.\
\n\nParameters\n----------\n"
"var_name : input string(len=-1)\n"
"\nOther Parameters\n----------------\n"
"cp__in : input float\n"
"cv__in : input float";
/*  */
static PyObject *f2py_rout_unified_microphysics_microphysics_register_register_compressible_species(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string var_name = NULL;
  int slen(var_name);
  PyObject *var_name_capi = Py_None;
  double cp__in = 0;
  PyObject *cp__in_capi = Py_None;
  double cv__in = 0;
  PyObject *cv__in_capi = Py_None;
  static char *capi_kwlist[] = {"var_name","cp__in","cv__in",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|OO:unified_microphysics.microphysics_register.register_compressible_species",\
    capi_kwlist,&var_name_capi,&cp__in_capi,&cv__in_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable var_name */
  slen(var_name) = -1;
  f2py_success = string_from_pyobj(&var_name,&slen(var_name),"",var_name_capi,"string_from_pyobj failed in converting 1st argument `var_name' of unified_microphysics.microphysics_register.register_compressible_species to C string");
  if (f2py_success) {
  /* Processing variable cp__in */
  if (cp__in_capi != Py_None)
    f2py_success = double_from_pyobj(&cp__in,cp__in_capi,"unified_microphysics.microphysics_register.register_compressible_species() 1st keyword (cp__in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cv__in */
  if (cv__in_capi != Py_None)
    f2py_success = double_from_pyobj(&cv__in,cv__in_capi,"unified_microphysics.microphysics_register.register_compressible_species() 2nd keyword (cv__in) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(var_name,&cp__in,&cv__in,slen(var_name));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of cv__in*/
  /* End of cleaning variable cv__in */
  } /*if (f2py_success) of cp__in*/
  /* End of cleaning variable cp__in */
    STRINGFREE(var_name);
  }  /*if (f2py_success) of var_name*/
  /* End of cleaning variable var_name */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************** end of register_compressible_species ********************/

/********************** register_incompressible_species **********************/
static char doc_f2py_rout_unified_microphysics_microphysics_register_register_incompressible_species[] = "\
register_incompressible_species(var_name,n_moments,[cp__in,cv__in])\n\nWrapper for ``register_incompressible_species``.\
\n\nParameters\n----------\n"
"var_name : input string(len=-1)\n"
"n_moments : input int\n"
"\nOther Parameters\n----------------\n"
"cp__in : input float\n"
"cv__in : input float";
/*  */
static PyObject *f2py_rout_unified_microphysics_microphysics_register_register_incompressible_species(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string var_name = NULL;
  int slen(var_name);
  PyObject *var_name_capi = Py_None;
  int n_moments = 0;
  PyObject *n_moments_capi = Py_None;
  double cp__in = 0;
  PyObject *cp__in_capi = Py_None;
  double cv__in = 0;
  PyObject *cv__in_capi = Py_None;
  static char *capi_kwlist[] = {"var_name","n_moments","cp__in","cv__in",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OO:unified_microphysics.microphysics_register.register_incompressible_species",\
    capi_kwlist,&var_name_capi,&n_moments_capi,&cp__in_capi,&cv__in_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable var_name */
  slen(var_name) = -1;
  f2py_success = string_from_pyobj(&var_name,&slen(var_name),"",var_name_capi,"string_from_pyobj failed in converting 1st argument `var_name' of unified_microphysics.microphysics_register.register_incompressible_species to C string");
  if (f2py_success) {
  /* Processing variable n_moments */
    f2py_success = int_from_pyobj(&n_moments,n_moments_capi,"unified_microphysics.microphysics_register.register_incompressible_species() 2nd argument (n_moments) can't be converted to int");
  if (f2py_success) {
  /* Processing variable cp__in */
  if (cp__in_capi != Py_None)
    f2py_success = double_from_pyobj(&cp__in,cp__in_capi,"unified_microphysics.microphysics_register.register_incompressible_species() 1st keyword (cp__in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable cv__in */
  if (cv__in_capi != Py_None)
    f2py_success = double_from_pyobj(&cv__in,cv__in_capi,"unified_microphysics.microphysics_register.register_incompressible_species() 2nd keyword (cv__in) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(var_name,&n_moments,&cp__in,&cv__in,slen(var_name));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of cv__in*/
  /* End of cleaning variable cv__in */
  } /*if (f2py_success) of cp__in*/
  /* End of cleaning variable cp__in */
  } /*if (f2py_success) of n_moments*/
  /* End of cleaning variable n_moments */
    STRINGFREE(var_name);
  }  /*if (f2py_success) of var_name*/
  /* End of cleaning variable var_name */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************* end of register_incompressible_species *******************/

/************************************ init ************************************/
static char doc_f2py_rout_unified_microphysics_microphysics_pylib_init[] = "\
init(microphysics_name)\n\nWrapper for ``init``.\
\n\nParameters\n----------\n"
"microphysics_name : input string(len=-1)";
/*  */
static PyObject *f2py_rout_unified_microphysics_microphysics_pylib_init(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string microphysics_name = NULL;
  int slen(microphysics_name);
  PyObject *microphysics_name_capi = Py_None;
  static char *capi_kwlist[] = {"microphysics_name",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:unified_microphysics.microphysics_pylib.init",\
    capi_kwlist,&microphysics_name_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable microphysics_name */
  slen(microphysics_name) = -1;
  f2py_success = string_from_pyobj(&microphysics_name,&slen(microphysics_name),"",microphysics_name_capi,"string_from_pyobj failed in converting 1st argument `microphysics_name' of unified_microphysics.microphysics_pylib.init to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(microphysics_name,slen(microphysics_name));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(microphysics_name);
  }  /*if (f2py_success) of microphysics_name*/
  /* End of cleaning variable microphysics_name */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of init ********************************/

/********************************** calc_dq **********************************/
static char doc_f2py_rout_unified_microphysics_microphysics_pylib_calc_dq[] = "\
dq_g,dq_tr = calc_dq(q_g,q_tr,dt,temp,pressure,[n_gases,n_solids,n_moments__max])\n\nWrapper for ``calc_dq``.\
\n\nParameters\n----------\n"
"q_g : input rank-1 array('d') with bounds (n_gases)\n"
"q_tr : input rank-2 array('d') with bounds (n_solids,n_moments__max)\n"
"dt : input float\n"
"temp : input float\n"
"pressure : input float\n"
"\nOther Parameters\n----------------\n"
"n_gases : input int, optional\n    Default: len(q_g)\n"
"n_solids : input int, optional\n    Default: shape(q_tr,0)\n"
"n_moments__max : input int, optional\n    Default: shape(q_tr,1)\n"
"\nReturns\n-------\n"
"dq_g : rank-1 array('d') with bounds (n_gases)\n"
"dq_tr : rank-2 array('d') with bounds (n_solids,n_moments__max)";
/*  */
static PyObject *f2py_rout_unified_microphysics_microphysics_pylib_calc_dq(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *q_g = NULL;
  npy_intp q_g_Dims[1] = {-1};
  const int q_g_Rank = 1;
  PyArrayObject *capi_q_g_tmp = NULL;
  int capi_q_g_intent = 0;
  PyObject *q_g_capi = Py_None;
  double *q_tr = NULL;
  npy_intp q_tr_Dims[2] = {-1, -1};
  const int q_tr_Rank = 2;
  PyArrayObject *capi_q_tr_tmp = NULL;
  int capi_q_tr_intent = 0;
  PyObject *q_tr_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  double temp = 0;
  PyObject *temp_capi = Py_None;
  double pressure = 0;
  PyObject *pressure_capi = Py_None;
  double *dq_g = NULL;
  npy_intp dq_g_Dims[1] = {-1};
  const int dq_g_Rank = 1;
  PyArrayObject *capi_dq_g_tmp = NULL;
  int capi_dq_g_intent = 0;
  double *dq_tr = NULL;
  npy_intp dq_tr_Dims[2] = {-1, -1};
  const int dq_tr_Rank = 2;
  PyArrayObject *capi_dq_tr_tmp = NULL;
  int capi_dq_tr_intent = 0;
  int n_gases = 0;
  PyObject *n_gases_capi = Py_None;
  int n_solids = 0;
  PyObject *n_solids_capi = Py_None;
  int n_moments__max = 0;
  PyObject *n_moments__max_capi = Py_None;
  static char *capi_kwlist[] = {"q_g","q_tr","dt","temp","pressure","n_gases","n_solids","n_moments__max",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOO:unified_microphysics.microphysics_pylib.calc_dq",\
    capi_kwlist,&q_g_capi,&q_tr_capi,&dt_capi,&temp_capi,&pressure_capi,&n_gases_capi,&n_solids_capi,&n_moments__max_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable q_g */
  ;
  capi_q_g_intent |= F2PY_INTENT_IN;
  capi_q_g_tmp = array_from_pyobj(NPY_DOUBLE,q_g_Dims,q_g_Rank,capi_q_g_intent,q_g_capi);
  if (capi_q_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(unified_microphysics_error,"failed in converting 1st argument `q_g' of unified_microphysics.microphysics_pylib.calc_dq to C/Fortran array" );
  } else {
    q_g = (double *)(capi_q_g_tmp->data);

  /* Processing variable temp */
    f2py_success = double_from_pyobj(&temp,temp_capi,"unified_microphysics.microphysics_pylib.calc_dq() 4th argument (temp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q_tr */
  ;
  capi_q_tr_intent |= F2PY_INTENT_IN;
  capi_q_tr_tmp = array_from_pyobj(NPY_DOUBLE,q_tr_Dims,q_tr_Rank,capi_q_tr_intent,q_tr_capi);
  if (capi_q_tr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(unified_microphysics_error,"failed in converting 2nd argument `q_tr' of unified_microphysics.microphysics_pylib.calc_dq to C/Fortran array" );
  } else {
    q_tr = (double *)(capi_q_tr_tmp->data);

  /* Processing variable pressure */
    f2py_success = double_from_pyobj(&pressure,pressure_capi,"unified_microphysics.microphysics_pylib.calc_dq() 5th argument (pressure) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"unified_microphysics.microphysics_pylib.calc_dq() 3rd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_gases */
  if (n_gases_capi == Py_None) n_gases = len(q_g); else
    f2py_success = int_from_pyobj(&n_gases,n_gases_capi,"unified_microphysics.microphysics_pylib.calc_dq() 1st keyword (n_gases) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(q_g)>=n_gases,"len(q_g)>=n_gases","1st keyword n_gases","calc_dq:n_gases=%d",n_gases) {
  /* Processing variable n_solids */
  if (n_solids_capi == Py_None) n_solids = shape(q_tr,0); else
    f2py_success = int_from_pyobj(&n_solids,n_solids_capi,"unified_microphysics.microphysics_pylib.calc_dq() 2nd keyword (n_solids) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(q_tr,0)==n_solids,"shape(q_tr,0)==n_solids","2nd keyword n_solids","calc_dq:n_solids=%d",n_solids) {
  /* Processing variable n_moments__max */
  if (n_moments__max_capi == Py_None) n_moments__max = shape(q_tr,1); else
    f2py_success = int_from_pyobj(&n_moments__max,n_moments__max_capi,"unified_microphysics.microphysics_pylib.calc_dq() 3rd keyword (n_moments__max) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(q_tr,1)==n_moments__max,"shape(q_tr,1)==n_moments__max","3rd keyword n_moments__max","calc_dq:n_moments__max=%d",n_moments__max) {
  /* Processing variable dq_tr */
  dq_tr_Dims[0]=n_solids,dq_tr_Dims[1]=n_moments__max;
  capi_dq_tr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dq_tr_tmp = array_from_pyobj(NPY_DOUBLE,dq_tr_Dims,dq_tr_Rank,capi_dq_tr_intent,Py_None);
  if (capi_dq_tr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(unified_microphysics_error,"failed in converting hidden `dq_tr' of unified_microphysics.microphysics_pylib.calc_dq to C/Fortran array" );
  } else {
    dq_tr = (double *)(capi_dq_tr_tmp->data);

  /* Processing variable dq_g */
  dq_g_Dims[0]=n_gases;
  capi_dq_g_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_dq_g_tmp = array_from_pyobj(NPY_DOUBLE,dq_g_Dims,dq_g_Rank,capi_dq_g_intent,Py_None);
  if (capi_dq_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(unified_microphysics_error,"failed in converting hidden `dq_g' of unified_microphysics.microphysics_pylib.calc_dq to C/Fortran array" );
  } else {
    dq_g = (double *)(capi_dq_g_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(q_g,q_tr,&dt,&temp,&pressure,dq_g,dq_tr,&n_gases,&n_solids,&n_moments__max);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_dq_g_tmp,capi_dq_tr_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_dq_g_tmp == NULL) ... else of dq_g*/
  /* End of cleaning variable dq_g */
  }  /*if (capi_dq_tr_tmp == NULL) ... else of dq_tr*/
  /* End of cleaning variable dq_tr */
  } /*CHECKSCALAR(shape(q_tr,1)==n_moments__max)*/
  } /*if (f2py_success) of n_moments__max*/
  /* End of cleaning variable n_moments__max */
  } /*CHECKSCALAR(shape(q_tr,0)==n_solids)*/
  } /*if (f2py_success) of n_solids*/
  /* End of cleaning variable n_solids */
  } /*CHECKSCALAR(len(q_g)>=n_gases)*/
  } /*if (f2py_success) of n_gases*/
  /* End of cleaning variable n_gases */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of pressure*/
  /* End of cleaning variable pressure */
  if((PyObject *)capi_q_tr_tmp!=q_tr_capi) {
    Py_XDECREF(capi_q_tr_tmp); }
  }  /*if (capi_q_tr_tmp == NULL) ... else of q_tr*/
  /* End of cleaning variable q_tr */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  if((PyObject *)capi_q_g_tmp!=q_g_capi) {
    Py_XDECREF(capi_q_g_tmp); }
  }  /*if (capi_q_g_tmp == NULL) ... else of q_g*/
  /* End of cleaning variable q_g */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of calc_dq *******************************/

/****************************** dimensions_valid ******************************/
static char doc_f2py_rout_unified_microphysics_microphysics_pylib_dimensions_valid[] = "\
ok = dimensions_valid(n_gases,n_solids,n_moments__max)\n\nWrapper for ``dimensions_valid``.\
\n\nParameters\n----------\n"
"n_gases : input int\n"
"n_solids : input int\n"
"n_moments__max : input int\n"
"\nReturns\n-------\n"
"ok : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_unified_microphysics_microphysics_pylib_dimensions_valid(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int dimensions_valid = 0;
  int n_gases = 0;
  PyObject *n_gases_capi = Py_None;
  int n_solids = 0;
  PyObject *n_solids_capi = Py_None;
  int n_moments__max = 0;
  PyObject *n_moments__max_capi = Py_None;
  static char *capi_kwlist[] = {"n_gases","n_solids","n_moments__max",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:unified_microphysics.microphysics_pylib.dimensions_valid",\
    capi_kwlist,&n_gases_capi,&n_solids_capi,&n_moments__max_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n_solids */
    f2py_success = int_from_pyobj(&n_solids,n_solids_capi,"unified_microphysics.microphysics_pylib.dimensions_valid() 2nd argument (n_solids) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n_moments__max */
    f2py_success = int_from_pyobj(&n_moments__max,n_moments__max_capi,"unified_microphysics.microphysics_pylib.dimensions_valid() 3rd argument (n_moments__max) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n_gases */
    f2py_success = int_from_pyobj(&n_gases,n_gases_capi,"unified_microphysics.microphysics_pylib.dimensions_valid() 1st argument (n_gases) can't be converted to int");
  if (f2py_success) {
  /* Processing variable dimensions_valid */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&dimensions_valid,&n_gases,&n_solids,&n_moments__max);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",dimensions_valid);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable dimensions_valid */
  } /*if (f2py_success) of n_gases*/
  /* End of cleaning variable n_gases */
  } /*if (f2py_success) of n_moments__max*/
  /* End of cleaning variable n_moments__max */
  } /*if (f2py_success) of n_solids*/
  /* End of cleaning variable n_solids */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of dimensions_valid **************************/

/******************************** init_called ********************************/
static char doc_f2py_rout_unified_microphysics_microphysics_pylib_init_called[] = "\
init_called = init_called()\n\nWrapper for ``init_called``.\
\n\nReturns\n-------\n"
"init_called : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_unified_microphysics_microphysics_pylib_init_called(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int init_called = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":unified_microphysics.microphysics_pylib.init_called",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable init_called */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&init_called);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",init_called);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable init_called */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of init_called *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_microphysics_constants_def[] = {
  {"L_cond",0,{{-1}},NPY_DOUBLE},
  {"cp_v",0,{{-1}},NPY_DOUBLE},
  {"cp_i",0,{{-1}},NPY_DOUBLE},
  {"rho_w",0,{{-1}},NPY_DOUBLE},
  {"cp_l",0,{{-1}},NPY_DOUBLE},
  {"R_v",0,{{-1}},NPY_DOUBLE},
  {"kreal",0,{{-1}},NPY_INT},
  {"ps0",0,{{-1}},NPY_DOUBLE},
  {"cp_d",0,{{-1}},NPY_DOUBLE},
  {"int8",0,{{-1}},NPY_INT},
  {"cv_d",0,{{-1}},NPY_DOUBLE},
  {"int4",0,{{-1}},NPY_INT},
  {"T0",0,{{-1}},NPY_DOUBLE},
  {"R_d",0,{{-1}},NPY_DOUBLE},
  {"cv_i",0,{{-1}},NPY_DOUBLE},
  {"epsmach",0,{{-1}},NPY_DOUBLE},
  {"cv_l",0,{{-1}},NPY_DOUBLE},
  {"real8",0,{{-1}},NPY_INT},
  {"kint",0,{{-1}},NPY_INT},
  {"cv_v",0,{{-1}},NPY_DOUBLE},
  {"real2",0,{{-1}},NPY_INT},
  {"real4",0,{{-1}},NPY_INT},
  {NULL}
};

static void f2py_setup_microphysics_constants(char *L_cond,char *cp_v,char *cp_i,char *rho_w,char *cp_l,char *R_v,char *kreal,char *ps0,char *cp_d,char *int8,char *cv_d,char *int4,char *T0,char *R_d,char *cv_i,char *epsmach,char *cv_l,char *real8,char *kint,char *cv_v,char *real2,char *real4) {
  int i_f2py=0;
  f2py_microphysics_constants_def[i_f2py++].data = L_cond;
  f2py_microphysics_constants_def[i_f2py++].data = cp_v;
  f2py_microphysics_constants_def[i_f2py++].data = cp_i;
  f2py_microphysics_constants_def[i_f2py++].data = rho_w;
  f2py_microphysics_constants_def[i_f2py++].data = cp_l;
  f2py_microphysics_constants_def[i_f2py++].data = R_v;
  f2py_microphysics_constants_def[i_f2py++].data = kreal;
  f2py_microphysics_constants_def[i_f2py++].data = ps0;
  f2py_microphysics_constants_def[i_f2py++].data = cp_d;
  f2py_microphysics_constants_def[i_f2py++].data = int8;
  f2py_microphysics_constants_def[i_f2py++].data = cv_d;
  f2py_microphysics_constants_def[i_f2py++].data = int4;
  f2py_microphysics_constants_def[i_f2py++].data = T0;
  f2py_microphysics_constants_def[i_f2py++].data = R_d;
  f2py_microphysics_constants_def[i_f2py++].data = cv_i;
  f2py_microphysics_constants_def[i_f2py++].data = epsmach;
  f2py_microphysics_constants_def[i_f2py++].data = cv_l;
  f2py_microphysics_constants_def[i_f2py++].data = real8;
  f2py_microphysics_constants_def[i_f2py++].data = kint;
  f2py_microphysics_constants_def[i_f2py++].data = cv_v;
  f2py_microphysics_constants_def[i_f2py++].data = real2;
  f2py_microphysics_constants_def[i_f2py++].data = real4;
}
extern void F_FUNC_US(f2pyinitmicrophysics_constants,F2PYINITMICROPHYSICS_CONSTANTS)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_microphysics_constants(void) {
  F_FUNC_US(f2pyinitmicrophysics_constants,F2PYINITMICROPHYSICS_CONSTANTS)(f2py_setup_microphysics_constants);
}


static FortranDataDef f2py_microphysics_common_def[] = {
  {"thermal_conductivity",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_common_thermal_conductivity,doc_f2py_rout_unified_microphysics_microphysics_common_thermal_conductivity},
  {"water_vapour_diffusivity",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_common_water_vapour_diffusivity,doc_f2py_rout_unified_microphysics_microphysics_common_water_vapour_diffusivity},
  {"saturation_vapour_pressure",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_common_saturation_vapour_pressure,doc_f2py_rout_unified_microphysics_microphysics_common_saturation_vapour_pressure},
  {NULL}
};

static void f2py_setup_microphysics_common(char *thermal_conductivity,char *water_vapour_diffusivity,char *saturation_vapour_pressure) {
  int i_f2py=0;
  f2py_microphysics_common_def[i_f2py++].data = thermal_conductivity;
  f2py_microphysics_common_def[i_f2py++].data = water_vapour_diffusivity;
  f2py_microphysics_common_def[i_f2py++].data = saturation_vapour_pressure;
}
extern void F_FUNC_US(f2pyinitmicrophysics_common,F2PYINITMICROPHYSICS_COMMON)(void (*)(char *,char *,char *));
static void f2py_init_microphysics_common(void) {
  F_FUNC_US(f2pyinitmicrophysics_common,F2PYINITMICROPHYSICS_COMMON)(f2py_setup_microphysics_common);
}


static FortranDataDef f2py_microphysics_register_def[] = {
  {"n_gases",0,{{-1}},NPY_INT},
  {"moments",1,{{-1}},NPY_INT},
  {"idx_dry_air",0,{{-1}},NPY_INT},
  {"n_moments__max",0,{{-1}},NPY_INT},
  {"n_solids",0,{{-1}},NPY_INT},
  {"idx_rain",0,{{-1}},NPY_INT},
  {"cv_solids",1,{{-1}},NPY_DOUBLE},
  {"idx_cice",0,{{-1}},NPY_INT},
  {"cv_gases",1,{{-1}},NPY_DOUBLE},
  {"idx_cwater",0,{{-1}},NPY_INT},
  {"cp_solids",1,{{-1}},NPY_DOUBLE},
  {"n_species",0,{{-1}},NPY_INT},
  {"idx_water_vapour",0,{{-1}},NPY_INT},
  {"idx_graupel",0,{{-1}},NPY_INT},
  {"cp_gases",1,{{-1}},NPY_DOUBLE},
  {"register_compressible_species",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_register_register_compressible_species,doc_f2py_rout_unified_microphysics_microphysics_register_register_compressible_species},
  {"register_incompressible_species",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_register_register_incompressible_species,doc_f2py_rout_unified_microphysics_microphysics_register_register_incompressible_species},
  {NULL}
};

static void f2py_setup_microphysics_register(char *n_gases,void (*moments)(int*,int*,void(*)(char*,int*),int*),char *idx_dry_air,char *n_moments__max,char *n_solids,char *idx_rain,void (*cv_solids)(int*,int*,void(*)(char*,int*),int*),char *idx_cice,void (*cv_gases)(int*,int*,void(*)(char*,int*),int*),char *idx_cwater,void (*cp_solids)(int*,int*,void(*)(char*,int*),int*),char *n_species,char *idx_water_vapour,char *idx_graupel,void (*cp_gases)(int*,int*,void(*)(char*,int*),int*),char *register_compressible_species,char *register_incompressible_species) {
  int i_f2py=0;
  f2py_microphysics_register_def[i_f2py++].data = n_gases;
  f2py_microphysics_register_def[i_f2py++].func = moments;
  f2py_microphysics_register_def[i_f2py++].data = idx_dry_air;
  f2py_microphysics_register_def[i_f2py++].data = n_moments__max;
  f2py_microphysics_register_def[i_f2py++].data = n_solids;
  f2py_microphysics_register_def[i_f2py++].data = idx_rain;
  f2py_microphysics_register_def[i_f2py++].func = cv_solids;
  f2py_microphysics_register_def[i_f2py++].data = idx_cice;
  f2py_microphysics_register_def[i_f2py++].func = cv_gases;
  f2py_microphysics_register_def[i_f2py++].data = idx_cwater;
  f2py_microphysics_register_def[i_f2py++].func = cp_solids;
  f2py_microphysics_register_def[i_f2py++].data = n_species;
  f2py_microphysics_register_def[i_f2py++].data = idx_water_vapour;
  f2py_microphysics_register_def[i_f2py++].data = idx_graupel;
  f2py_microphysics_register_def[i_f2py++].func = cp_gases;
  f2py_microphysics_register_def[i_f2py++].data = register_compressible_species;
  f2py_microphysics_register_def[i_f2py++].data = register_incompressible_species;
}
extern void F_FUNC_US(f2pyinitmicrophysics_register,F2PYINITMICROPHYSICS_REGISTER)(void (*)(char*,void (*)(int*,int*,void(*)(char*,int*),int*),char*,char*,char*,char*,void (*)(int*,int*,void(*)(char*,int*),int*),char*,void (*)(int*,int*,void(*)(char*,int*),int*),char*,void (*)(int*,int*,void(*)(char*,int*),int*),char*,char*,char*,void (*)(int*,int*,void(*)(char*,int*),int*),char *,char *));
static void f2py_init_microphysics_register(void) {
  F_FUNC_US(f2pyinitmicrophysics_register,F2PYINITMICROPHYSICS_REGISTER)(f2py_setup_microphysics_register);
}


static FortranDataDef f2py_microphysics_pylib_def[] = {
  {"init",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_pylib_init,doc_f2py_rout_unified_microphysics_microphysics_pylib_init},
  {"calc_dq",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_pylib_calc_dq,doc_f2py_rout_unified_microphysics_microphysics_pylib_calc_dq},
  {"dimensions_valid",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_pylib_dimensions_valid,doc_f2py_rout_unified_microphysics_microphysics_pylib_dimensions_valid},
  {"init_called",-1,{{-1}},0,NULL,(void *)f2py_rout_unified_microphysics_microphysics_pylib_init_called,doc_f2py_rout_unified_microphysics_microphysics_pylib_init_called},
  {NULL}
};

static void f2py_setup_microphysics_pylib(char *init,char *calc_dq,char *dimensions_valid,char *init_called) {
  int i_f2py=0;
  f2py_microphysics_pylib_def[i_f2py++].data = init;
  f2py_microphysics_pylib_def[i_f2py++].data = calc_dq;
  f2py_microphysics_pylib_def[i_f2py++].data = dimensions_valid;
  f2py_microphysics_pylib_def[i_f2py++].data = init_called;
}
extern void F_FUNC_US(f2pyinitmicrophysics_pylib,F2PYINITMICROPHYSICS_PYLIB)(void (*)(char *,char *,char *,char *));
static void f2py_init_microphysics_pylib(void) {
  F_FUNC_US(f2pyinitmicrophysics_pylib,F2PYINITMICROPHYSICS_PYLIB)(f2py_setup_microphysics_pylib);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "unified_microphysics",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_unified_microphysics(void) {
#else
#define RETVAL
PyMODINIT_FUNC initunified_microphysics(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = unified_microphysics_module = PyModule_Create(&moduledef);
#else
  m = unified_microphysics_module = Py_InitModule("unified_microphysics", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module unified_microphysics (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'unified_microphysics' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  microphysics_constants --- L_cond,cp_v,cp_i,rho_w,cp_l,R_v,kreal,ps0,cp_d,int8,cv_d,int4,T0,R_d,cv_i,epsmach,cv_l,real8,kint,cv_v,real2,real4""  microphysics_common --- thermal_conductivity(),water_vapour_diffusivity(),saturation_vapour_pressure()""  microphysics_register --- n_gases,moments,idx_dry_air,n_moments__max,n_solids,idx_rain,cv_solids,idx_cice,cv_gases,idx_cwater,cp_solids,n_species,idx_water_vapour,idx_graupel,cp_gases,register_compressible_species(),register_incompressible_species()""  microphysics_pylib --- init(),calc_dq(),dimensions_valid(),init_called()"".");
  PyDict_SetItemString(d, "__doc__", s);
  unified_microphysics_error = PyErr_NewException ("unified_microphysics.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));









/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "microphysics_pylib", PyFortranObject_New(f2py_microphysics_pylib_def,f2py_init_microphysics_pylib));
  PyDict_SetItemString(d, "microphysics_register", PyFortranObject_New(f2py_microphysics_register_def,f2py_init_microphysics_register));
  PyDict_SetItemString(d, "microphysics_common", PyFortranObject_New(f2py_microphysics_common_def,f2py_init_microphysics_common));
  PyDict_SetItemString(d, "microphysics_constants", PyFortranObject_New(f2py_microphysics_constants_def,f2py_init_microphysics_constants));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"unified_microphysics");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
